- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/components/Footer.jsx
- client/src/constants/index.js
- client/src/index.css
- client/src/main.jsx
- package-lock.json
- package.json
Added initial styling & added constants folder with index.js file. Updated index.css file and downloaded npm packages into client folder.
> Added initial styling

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/Pages/Booking.jsx
- client/src/components/Appointments.jsx
- client/src/components/OurWork.jsx
- client/src/constants/index.js
created botton functions to get to bookings page. 
placed some text on booking page as a place holder. 
styling still needed for bottons.
> added buttons to click to go to bookings page

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/Pages/Signup.jsx
- client/src/components/Appointments.jsx
- client/src/components/Home.jsx
- client/src/components/LoginModal.jsx
- client/src/components/Navbar.jsx
- client/src/constants/index.js
- client/src/utils/mutations.js
Sign-Up and Sign-In working, added a home component we can navigate thru sections being inside a different route (outside root), added a modal for the log-in section, added a signup page '/signup'
> Signup and Signin working

- client/src/components/Hero.jsx
- client/src/index.css
Added a light cream color for background, and removed bold from title in hero.
> changed background and title style

- client/src/Pages/KaylaPortfolio.jsx
- client/src/Pages/MalloryPortfolio.jsx
- client/src/Pages/MeganPortfolio.jsx
Started Stylist Portfolio Pages
> Started Stylist Portfolio Pages

- client/src/App.jsx
- client/src/Pages/KaylaPortfolio.jsx
- client/src/Pages/MalloryPortfolio.jsx
- client/src/Pages/MeganPortfolio.jsx
- client/src/components/Portfolio.jsx
- client/src/constants/index.js
Added routes for stylist profiles
> Stylist profiles

- client/src/components/Services.jsx
- client/src/index.css
hero was added to page, updated pricing list and placed booking button.
> added styling to services page and booking button

- client/src/Pages/KaylaPortfolio.jsx
- client/src/Pages/MalloryPortfolio.jsx
- client/src/Pages/MeganPortfolio.jsx
- client/src/components/LoginModal.jsx
- client/src/components/OurWork.jsx
- client/src/components/Reviews.jsx
- client/src/constants/index.js
- client/src/index.css
Improved NavBar & created stylist profiles
> Improved NavBar & created stylist profiles

- client/src/App.jsx
- client/src/Pages/Booking.jsx
- client/src/components/OurWork.jsx
- client/src/constants/index.js
- client/src/utils/mutations.js
- server/models/Appointment.js
- server/models/Service.js
- server/package-lock.json
- server/package.json
- server/schemas/resolvers.js
- server/schemas/typeDefs.js
- server/server.js
Bookings are being added to the database, pulling information of the available times and services working and handling error messages
> Bookings working

- client/src/Pages/KaylaPortfolio.jsx
- client/src/Pages/MalloryPortfolio.jsx
- client/src/Pages/MeganPortfolio.jsx
placed routes for the book now button to go to booking page. Placed bio information for each stylist.
> routed book now button and placed bios for stylist

- client/src/App.jsx
- client/src/Pages/AdminHome.jsx
- client/src/components/LoginModal.jsx
- client/src/utils/mutations.js
created file for admin view and editing 
fixed route from sign up model to go to sign up if an account set up is needed.
> created admin file and tables, fixed route to sign up page from login

- client/src/App.jsx
- client/src/Pages/AdminHome.jsx
- client/src/Pages/AdminServices.jsx
- client/src/utils/mutations.js
create ad delete  the service on the admin page
> create and delete service

- client/src/constants/index.js
Fixed typo on navbar, from stylist to stylists
> Fixed typo on navbar, from stylist to stylists

- client/src/components/Navbar.jsx
Added scroll-up button to body so when users click it they will be taken to the  very top of the page
> Added scroll-up button to body so when users click it they will be taken to the top of the page "navbar"

- client/src/Pages/Signup.jsx
- client/src/index.css
> Styled sign up form

- client/src/components/LoginModal.jsx
modal is not covered by pictures on website and closes if user click anywhere outside of it
> SignUp modal fixed

- client/src/Pages/About.jsx
- client/src/Pages/Booking.jsx
- client/src/Pages/KaylaPortfolio.jsx
- client/src/Pages/MalloryPortfolio.jsx
- client/src/Pages/MeganPortfolio.jsx
- client/src/Pages/Signup.jsx
- client/src/components/Footer.jsx
- client/src/components/LoginModal.jsx
- client/src/components/Navbar.jsx
- client/src/index.css
Added links to navigate stylist profiles, styled sign up form, added logo to navbar, styled book appointment, created about page and added navigation buttons
> Stylists pages fix

- client/src/Pages/KaylaPortfolio.jsx
- client/src/Pages/MalloryPortfolio.jsx
- client/src/Pages/MeganPortfolio.jsx
- client/src/constants/index.js
> fixed stylists routes

- client/src/components/OurWork.jsx
- client/src/constants/index.js
add photos to lightbox gallery to show hair stylist work.
> added photos to ourwork gallery

- client/src/Pages/KaylaPortfolio.jsx
- client/src/Pages/MalloryPortfolio.jsx
- client/src/Pages/MeganPortfolio.jsx
changed img src on profile in an attempt to fix photos not showing on deployed site properly
> updated image src to fix photo bug

- client/src/components/Navbar.jsx
- client/src/constants/index.js
> Navbar links

- client/src/App.jsx
- client/src/components/Navbar.jsx
- client/src/constants/index.js
attempted to fix bug for admin nav bar to show admin needed items. was able to get navbar to show again on landing page however the admin navbar only show once page is refreshed. still needs to be fixed.
> attempted to fix admin navbar

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/Pages/StylistsDashboard.jsx
- client/src/components/AdminCal.jsx
- client/src/utils/calendar.css
calendar added to stylist dashboard. not linked to any data or backend atm. this was just front end display.
> Big calendar user

- client/src/App.jsx
- client/src/Pages/AdminStylists.jsx
- client/src/components/LoginModal.jsx
- client/src/components/Navbar.jsx
- client/src/constants/index.js
> Added all links to navbar

- client/src/Pages/UserDashboard.jsx
table created on the users dashboard
> Table created on the users dashboard
